FROM node:22-alpine

WORKDIR /app

# ONLY copy the PACKAGE JSON to the app directory in the container
COPY ./ package.json ./ 

# then install
RUN npm install

# then COPY EVERYTHING
COPY ./ ./

CMD ["npm", "start"]